d_model: 256
n_gqa_groups: 1
n_heads: 4
d_queries: 32
d_values: 32
d_inner: 1024
use_infinite_attention: false
use_moe: false
n_encoder_layers: 3
n_decoder_layers: 3
dropout: 0.1

use_amp: false
dtype: float32

positional_encoding_type: rotary
positional_encoding_dim: 32
learnable_positional_encoding: false

encoder_param_sharing_type: none
decoder_param_sharing_type: none
m_encoder_independent_layers: 0
m_decoder_independent_layers: 0
activation_function: relu
